import React, { useState, useEffect, useCallback } from "react";
import "./App.css";
import "./index.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

/**
 * PUBLIC_INTERFACE
 * Cohesive application shell for EchoGuard with Sidebar, Header, and support for dark mode + responsive layout.
 */
function App() {
  // Sidebar state for mobile
  const [sidebarOpen, setSidebarOpen] = useState(false);

  // Track the active navigation tab
  const [activeTab, setActiveTab] = useState(0);

  // Dark mode: default to system preference, can be toggled (future feature)
  useEffect(() => {
    if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
      document.documentElement.classList.add("dark");
    }
  }, []);

  // Close sidebar if resizing to desktop
  useEffect(() => {
    function handleResize() {
      if (window.innerWidth >= 768) setSidebarOpen(false);
    }
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // Navigation tab names for page title/heading demo
  const tabContent = [
    {
      title: "Dashboard",
      subtitle: "Your Real-Time Exposure & Privacy Overview",
      desc:
        "Gain rapid insight into your digital privacy, exposure score, and real-time alerts. Visual dashboards keep you informed and aware.",
      action: <button className="btn btn-large">Run Digital Scan</button>,
    },
    {
      title: "Action Plan",
      subtitle: "AI Privacy Tips & Dynamic Checklist",
      desc:
        "Follow personalized steps generated by EchoGuard’s AI to boost your privacy, complete checklists, and monitor your privacy streak.",
      action: <button className="btn btn-large">View My Tips</button>,
    },
    {
      title: "Digital Twin",
      subtitle: "Monitor Your Digital Identity Across the Web",
      desc:
        "Visualize your online identity, where your images or data appear, and review stylometric matches in real time.",
      action: <button className="btn btn-large">View Matched Profiles</button>,
    },
    {
      title: "Alerts",
      subtitle: "Data Breach & Privacy Alert Timeline",
      desc:
        "Stay updated on new leaks, critical vulnerabilities, or social graph risks. Take instant action on alerts.",
      action: <button className="btn btn-large">See All Alerts</button>,
    },
    {
      title: "Settings",
      subtitle: "Configure Devices, Security, & Preferences",
      desc:
        "Manage device sync, connected apps, privacy manifesto and notifications. Download audit reports with 1 click.",
      action: <button className="btn btn-large">Settings</button>,
    },
  ];

  // Handlers
  const toggleSidebar = useCallback(() => setSidebarOpen(v => !v), []);
  const handleTabChange = idx => setActiveTab(idx);

  return (
    <div className="app flex bg-background dark:bg-[#181826] min-h-screen">
      {/* Sidebar */}
      <Sidebar
        isMobileOpen={sidebarOpen}
        toggleMobile={toggleSidebar}
        activeTab={activeTab}
        onTabChange={handleTabChange}
      />
      {/* Main area */}
      <div className="flex flex-col flex-1 min-h-screen transition-colors bg-background dark:bg-[#181826]">
        {/* Header */}
        <Header onMenuClick={toggleSidebar} />

        {/* Page content */}
        <main className="flex-1 w-full pt-6 px-4 md:pl-0 md:ml-0 max-w-5xl mx-auto">
          <div className="py-8">
            <div className="mb-2">
              <div className="subtitle text-accent text-lg font-semibold tracking-wide mb-2">
                {tabContent[activeTab].subtitle}
              </div>
              <h1 className="title font-bold text-3xl md:text-5xl text-primary mb-1 leading-tight">
                {tabContent[activeTab].title}
              </h1>
              <div className="description mb-6 text-text-secondary text-md md:w-3/4">
                {tabContent[activeTab].desc}
              </div>
              <div>{tabContent[activeTab].action}</div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

export default App;